// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cloc(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['cloc']['AppCloc']['Cloc'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function GetAppName() {
  return window['go']['cloc']['AppCloc']['GetAppName']();
}

export function SelectDirectory() {
  return window['go']['cloc']['AppCloc']['SelectDirectory']();
}

export function Startup(arg1) {
  return window['go']['cloc']['AppCloc']['Startup'](arg1);
}
