// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Cloc(arg1:boolean,arg2:boolean,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string):Promise<string>;

export function GetAppName():Promise<string>;

export function SelectDirectory():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
